#!/bin/sh
#
# PROVIDE: geth
# REQUIRE: networking
# KEYWORD:

. /etc/rc.subr

name="geth"
rcvar="geth_enable"
geth_user="ethereum"
geth_command="/home/ethereum/go-ethereum/build/bin/geth --datadir \"/home/ethereum/.ethereum\" --metrics --maxpeers 300"
pidfile="/tmp/${name}.pid"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -R 60 -o /tmp/geth.log -f ${geth_command}"

load_rc_config $name
: ${geth_enable:=no}

run_rc_command "$1"

